문제:
`DAILY_SALES` 테이블에 새로운 데이터를 삽입하는 SQL 문을 작성하세요. 날짜는 '2024-09-01'이고, 총 판매 금액은 10000으로 입력하세요.

답안: 

-- DAILY_SALES 테이블 생성
CREATE TABLE DAILY_SALES (
  SALE_DATE DATE,
  TOTAL_SALES NUMBER
);

-- DAILY_SALES 테이블에 속성, 값 추가
INSERT INTO DAILY_SALES(SALE_DATE, TOTAL_SALES) 
VALUES (TO_DATE('2024-09-01', 'YYYY-MM-DD'), 7000);
INSERT INTO DAILY_SALES(SALE_DATE, TOTAL_SALES) 
VALUES (TO_DATE('2024-09-02', 'YYYY-MM-DD'), 10000);
INSERT INTO DAILY_SALES(SALE_DATE, TOTAL_SALES) 
VALUES (TO_DATE('2024-09-03', 'YYYY-MM-DD'), 10000);


-- SELECT 문을 통해 결과 확인
SELECT * 
FROM DAILY_SALES;
