문제:
SELECT와 GROUP BY를 활용한 집계 쿼리 작성 (35점)
`판매 테이블(SALES)`에서 날짜별 총 판매 금액을 계산하는 SQL 쿼리를 작성하세요.

-- sales 테이블 생성
CREATE TABLE SALES (
    SALE_ID NUMBER,
    SALE_DATE DATE,
    SALE_AMOUNT NUMBER,
    PRODUCT_ID NUMBER,
    CUSTOMER_ID NUMBER
);

INSERT INTO SALES (SALE_ID, SALE_DATE, SALE_AMOUNT, PRODUCT_ID, CUSTOMER_ID) 
VALUES (1, TO_DATE('2024-09-01', 'YYYY-MM-DD'), 5000, 101, 1001);

INSERT INTO SALES (SALE_ID, SALE_DATE, SALE_AMOUNT, PRODUCT_ID, CUSTOMER_ID) 
VALUES (2, TO_DATE('2024-09-01', 'YYYY-MM-DD'), 2000, 102, 1002);

INSERT INTO SALES (SALE_ID, SALE_DATE, SALE_AMOUNT, PRODUCT_ID, CUSTOMER_ID) 
VALUES (3, TO_DATE('2024-09-02', 'YYYY-MM-DD'), 7000, 101, 1003);

INSERT INTO SALES (SALE_ID, SALE_DATE, SALE_AMOUNT, PRODUCT_ID, CUSTOMER_ID) 
VALUES (4, TO_DATE('2024-09-02', 'YYYY-MM-DD'), 3000, 103, 1004);

INSERT INTO SALES (SALE_ID, SALE_DATE, SALE_AMOUNT, PRODUCT_ID, CUSTOMER_ID) 
VALUES (5, TO_DATE('2024-09-03', 'YYYY-MM-DD'), 10000, 102, 1005);

답안: 

-- 날짜별 총 판매 금액을 계산하는 SQL 쿼리
SELECT SALE_DATE, SUM(SALE_AMOUNT) AS TOTAL_SALES
FROM SALES
GROUP BY SALE_DATE;

-- 특정 날짜만 필터링 하여 총 판매 금액을 계산하는 SQL 쿼리
SELECT SALE_DATE, SUM(SALE_AMOUNT) AS TOTAL_SALES
FROM SALES
WHERE SALE_DATE = TO_DATE('2024-09-01', 'YYYY-MM-DD')
GROUP BY SALE_DATE;

SELECT * 
FROM DAILY_SALES;

